# Generated by Django 5.1.4 on 2025-01-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=30, verbose_name='Steam app id')),
                ('name', models.CharField(max_length=255, verbose_name='Steam app name')),
                ('playtime_forever', models.CharField(max_length=30, verbose_name='User play hours')),
                ('status', models.CharField(choices=[('sc1', 'Passed'), ('sc2', 'Not finished'), ('sc3', 'Drop'), ('sc4', 'Not started')], default='sc4', max_length=55, verbose_name='Gameplay status')),
                ('local_rating', models.CharField(choices=[('gmc1', '1'), ('gmc2', '2'), ('gmc3', '3'), ('gmc4', '4'), ('gmc5', '5')], default='1', max_length=10, verbose_name='Your game rating')),
                ('local_review', models.CharField(max_length=550, verbose_name='Your local game review')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
