# Generated by Django 5.1.4 on 2025-01-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.CharField(max_length=30, verbose_name='Steam app id')),
                ('name', models.CharField(max_length=255, verbose_name='Steam app name')),
                ('playtime_forever', models.CharField(max_length=30, verbose_name='User play hours')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
