# Generated by Django 5.1.4 on 2025-01-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipsteam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('sc1', 'Passed'), ('sc2', 'Not finished'), ('sc3', 'Drop'), ('sc4', 'Not started')], default='Not started', max_length=55, verbose_name='Gameplay status'),
        ),
    ]
